# Generated by Django 4.0.1 on 2022-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_assetsdetail_industry_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsdetail',
            name='industry_code',
            field=models.IntegerField(),
        ),
    ]
